# Generated by Django 4.0.7 on 2022-09-14 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='c_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
